services:
  - type: worker
    name: leps-casino-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: TON_API_KEY
        sync: false
      - key: ROCKET_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: COLLECTION_WALLET
        sync: false
      - key: WITHDRAWAL_FEE
        value: "0.05"
